### PR TITLE
Predefined URL in `avatar` to prevent error

### PR DESCRIPTION
**Pull request by iHeroGH**
Command raised an exception: UnboundLocalError: local variable 'url' referenced before assignment

### CODE REVIEW

**Comment by irismessage** [comment]
How did this happen anyway?

**Comment by iHeroGH** [comment]
> How did this happen anyway?

The avatar command was updated to allow for enlarging emojis I think, so the URL variable was now initialized within an if-elif statement

**Comment by irismessage** [comment]
> 
> 
> > How did this happen anyway?
> 
> The avatar command was updated to allow for enlarging emojis I think, so the URL variable was now initialized within an if-elif statement

But how was `target` not an instance of `(discord.User, discord.Member)` or `(discord.Emoji, discord.PartialEmoji)`? The argument is `target:typing.Union[discord.User, discord.PartialEmoji]=None`, so shouldn't there have been a conversion error instead? Besides, I saw the invocation and I know it was passed a user ping

**Comment by iHeroGH** [comment]
Rechecked - it works for pinging anything other than the bot (I've noticed this before, pinging the bot with discord.User converters is kinda wonky(?)). This pull request won't do anything

**Comment by 4Kaylum** [comment]
Closed with #195.

**Pull request closed without merging**
