### PR TITLE
made bot more confident

### PR DESCRIPTION
**Pull request by ghost**
changed "should be" to "estimated to be around"

### CODE REVIEW

**Review by irismessage — COMMENTED** [review]
Doesn't make sense

**Comment by ghost** [comment]
> Doesn't make sense

"Should be" is used if the bot is giving a guess, but the bot is using an algorithm/function to get the timezone of everybody, so it must be "Estimated to be" since it's estimating their time with the given timezone

**Comment by irismessage** [comment]
> 
> 
> > Doesn't make sense
> 
> "Should be" is used if the bot is giving a guess, but the bot is using an algorithm/function to get the timezone of everybody, so it must be "Estimated to be" since it's estimating their time with the given timezone

No, it's not an estimate if it's getting a definite time based on the stored timezone. It's 'should be' because it will be right as long as they've set their timezone

**Comment by ghost** [comment]
> > > Doesn't make sense
> > 
> > 
> > "Should be" is used if the bot is giving a guess, but the bot is using an algorithm/function to get the timezone of everybody, so it must be "Estimated to be" since it's estimating their time with the given timezone
> 
> No, it's not an estimate if it's getting a definite time based on the stored timezone. It's 'should be' because it will be right as long as they've set their timezone

At that point, why not just say "Your time is" instead of "Your time should be"

**Comment by 4Kaylum** [comment]
I'm fine with the text as PR'd.

**Comment by ghost** [comment]
> I'm fine with the text as PR'd.

thanks! 💖

**Pull request merged**
