### PR TITLE
Change homepage to the package url

### PR DESCRIPTION
**Pull request by fadedmax**
let’s fukin go

### CODE REVIEW

**Comment by Silverdimond** [comment]
image
image
max this breaks urls
image
i think #45 fixes it idk

**Comment by fadedmax** [comment]
@Silverdimond 
image

you actually did your package search wrong, its discord.net not discord.

**Comment by Silverdimond** [comment]
That was intentional

**Comment by fadedmax** [comment]
Have you tested this code yet?

**Comment by Silverdimond** [comment]
What code?

**Pull request merged**
